// A '.tsx' file enables JSX support in the TypeScript compiler,
// for more information see the following page on the TypeScript wiki:
// https://github.com/Microsoft/TypeScript/wiki/JSX

/**
 * 登录用
 */
export const USER_LOG_ON = "USER_LOG_ON";
export const USER_LOG_OFF = "USER_LOG_OFF";
/**
 * 用户信息用
 */
export const GET_USER_POSTS = "GET_USER_POSTS";
export const CHANGE_USERINFO = "CHANGE_USERINFO";
export const CHANGE_VISITING_USER = "CHANGE_VISITING_USER";
export const CHANGE_USER_FAVORITE_BOARDS = "CHANGE_USER_FAVORITE_BOARDS";
export const CHANGE_USER_FAVORITE_POSTS = "CHANGE_USER_FAVORITE_POSTS";
export const CHANGE_USER_FANS_INFO = "CHANGE_USER_FANS_INFO";
export const CHANGE_USER_FOLLOWINGS_INFO = "CHANGE_USER_FOLLOWINGS_INFO";
export const CHANGE_USER_RECENT_TOPICS = "CHANGE_USER_RECENT_TOPICS";
export const CHANGE_USER_RECENT_POSTS = "CHANGE_USER_RECENT_POSTS";
export const CHANGE_USER_HOT_POSTS = "CHANGE_USER_HOT_POSTS";
export const CHNAGE_USER_CENTER_PAGE = "CHNAGE_USER_CENTER_PAGE";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const USER_CENTER_LOADING = "USER_CENTER_LOADING";
export const USER_CENTER_LOADED = "USER_CENTER_LOADED";
export const USER_CENTER_FETCH_ERROR = "USER_CENTER_FETCH_ERROR";
export const USER_CENTER_SOLVE_ERROR = "USER_CENTER_SOLVE_ERROR";
export const USER_CENTER_PAGE_LOAD_UNFINISH = "USER_CENTER_PAGE_LOAD_UNFINISH";
export const USER_CENTER_PAGE_LOAD_FINISH = "USER_CENTER_PAGE_LOAD_FINISH";
export const USER_CENTER_FOLLOW_USER = "USER_CENTER_FOLLOW_USER";
export const USER_CENTER_UNFOLLOW_USER = "USER_CENTER_UNFOLLOW_USER";
export const USER_CENTER_TRANSFER_WEALTH_SUCCESS =
  "USER_CENTER_TRANSFER_WEALTH_SUCCESS";
export const USER_CENTER_FAVORITE_GROUP_CHANGE = "USER_CENTER_FAVORITE_GROUP_CHANGE";
/**
 * 抛出错误
 */
export const THROW_ERROR = "THROW_ERROR";
export const SOLVE_ERROR = "SOLVE_ERROR";
/**
 * 帖子
 */
export const ADD_AWARD = "ADD_AWARD";

export const CHANGE_MESSAGE_COUNT = "CHANGE_MESSAGE_COUNT";
